### PR TITLE
Fix an issue where Apple Calendar wouldn't show a map even though coo…

### PR DESCRIPTION
**Pull request by Mauricevb**
This PR fixes an issue where Apple Calendar wouldn't show a map even though coordinates were provided. This happened because the coordinates in the 'Apple Structured Location string' were set incorrectly. 

**Before** this fix the library would generate:

```
X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-APPLE-RADIUS=70.5;
X-TITLE="Street\nCity, Country":51.643068;4.855145
```

**After** the fix:
```
X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-APPLE-RADIUS=70.5;
X-TITLE="Street\nCity, Country":geo:51.643068,4.855145
```

Notice the `geo:` prefix and the comma (`,`) instead of semicolon (`;`) between the two numbers.

This change results in the map now being showed in Apple Calendar:
Screenshot

**About my fix**
I think there were two solutions for this issue. One would be to change `CoordinatesProperty` and set an optional prefix (`geo:`) and delimiter (`,`/`:`) in the constructor. The second solution would be creating a new property class called `AppleLocationCoordinatesProperty` that generates the correct value for the 'Apple Structured Location string'. I chose the latter as these changes were made for the 'Apple Structured Location string' specifically and the changes in solution 1 wouldn't be used in other places.

### CODE REVIEW

**Comment by rubenvanassche** [comment]
Hi @Mauricevb,

Good call to make a different class specific for Apple calendar, could you rework the class to look more like this:

```php
$property = AppleLocationCoordinatesProperty::create(
             $this->lat,
             $this->lng,
             $this->address,
             $this->addressName
             72 // Let's make this radius optional
        );
```

Instead of this:

```php
$property = AppleLocationCoordinatesProperty::create(
             'X-APPLE-STRUCTURED-LOCATION',
             $this->lat,
             $this->lng
        )->addParameter(Parameter::create('VALUE', 'URI'))
            ->addParameter(Parameter::create('X-ADDRESS', $this->address))
            ->addParameter(Parameter::create('X-APPLE-RADIUS', 72))
            ->addParameter(Parameter::create('X-TITLE', $this->addressName));
```

That way we have a specific object for locations in Apple Calendars and can test it quite easily.

Thanks!

**Comment by Mauricevb** [comment]
Hi @rubenvanassche,

I updated the code and made the changes you suggested :)

Maurice

**Comment by rubenvanassche** [comment]
Whoa @Mauricevb that was quick! Could you add a test like this one: https://github.com/spatie/icalendar-generator/blob/master/tests/Properties/CoordinatesPropertyTest.php for the new `AppleLocationCoordinatesProperty`? Then I can merge it and tag a release.

**Comment by Mauricevb** [comment]
@rubenvanassche  Oops, I forgot to update the tests indeed. Just created a new test for the new `AppleLocationCoordinatesProperty`, updated an existing test and updated the integration test file. All tests pass now :)

**Comment by rubenvanassche** [comment]
Thanks @Mauricevb, this looks awesome!

**Pull request merged**
